{{- if eq (include "games.certAvailable" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: games-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ (include "games.cert.publicKey") | toString | b64enc | quote }}
  tls.key: {{ (include "games.cert.privateKey") | toString | b64enc | quote }}
{{- end -}}
