apiVersion: v1
kind: Service
metadata:
  name: games
spec:
  type: NodePort
  selector:
    app: games
  ports:
    {{- if .Values.certificate }}
    - port: 443
      name: https
      targetPort: https
    {{- else }}
    - port: 80
      name: http
      targetPort: http
    {{- end }}
      nodePort: {{ .Values.service.nodePort }}
