apiVersion: apps/v1
kind: Deployment
metadata:
  name: compression-utils
spec:
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: compression-utils
  template:
    metadata:
      labels:
        app: compression-utils
    spec:
      containers:
        - name: ubuntu
          command:
          - bash
          - -c
          - |
            export TZ=Etc/UTC && \
            ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
            apt-get update && \
            apt-get install \
              -y \
              p7zip \
              zip \
              unzip \
              unrar \
              mc \
              vim \
            && while true; do sleep 300; done
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
