apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome-cdp
spec:
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: chrome-cdp
  template:
    metadata:
      labels:
        app: chrome-cdp
    spec:
      containers:
        - name: chrome
          args:
          - --headless
          - --disable-gpu
          - --no-sandbox
          - --disable-audio-output
          - --remote-debugging-address=0.0.0.0
          - --remote-debugging-port=9222
          - --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          livenessProbe:
            tcpSocket:
              port: 9222
          securityContext:
            capabilities:
              add:
              - SYS_ADMIN
            privileged: true
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 9222
              name: chrome
      hostIPC: true
